version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - /C/Grid3:/etc/selenoid
      - /C/Grid3/video:/opt/selenoid/video
      - /var/run/docker.sock:/var/run/docker.sock
      - /C/Grid3/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Grid3/video
    command: ["-conf", "-vnc", "-conf", "/etc/selenoid/browsers.json", "-limit", "14", "-timeout", "9m", "-session-attempt-timeout", "10m", "-service-startup-timeout", "10m", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  chrome:
    image: "selenoid/vnc:chrome_76.0"
    network_mode: bridge
    links:
      - selenoid      
  video:
    image: "selenoid/video-recorder:latest-release"
    network_mode: bridge
    links:
      - selenoid
    
      